---
title: 'CFS `r paste(format(Sys.time(),"%Y-%m-%d %H:%M:%S") , commandArgs(trailingOnly=T)[1])` + Norms 1991-2020 (Reana NCEP)'
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    lightbox: true
    theme: united
---

```{r setup, include=FALSE}

# commandArgs(trailingOnly=T)[1] Location Name
# commandArgs(trailingOnly=T)[2] Profile Name
# commandArgs(trailingOnly=T)[3] Day Ago
# commandArgs(trailingOnly=T)[4] TZ

prof_name = commandArgs(trailingOnly = T)[2]
day_ago = as.integer(commandArgs(trailingOnly = T)[3])
the_tz = as.integer(commandArgs(trailingOnly = T)[4])

library(flexdashboard)
library(lubridate)
library(ggplot2)
library(gridExtra)
library(DescTools)
library(viridis) 

library(lubridate)
library(DescTools)
library(spatstat.utils)
library(scales)

library(TSrepr)
library(ggplot2)
library(data.table)
library(cluster)
library(clusterCrit)
library(zoo)
library(reshape)
library(RColorBrewer)
library(stringr)
```

```{r}



YEAR <- as.integer(format(Sys.time(), "%Y"))


# norms <- data.frame(
#   DATE = c(format(
#     as.POSIXlt(norm_ncep$DATE, format = "%d/%m"),
#     paste0(sprintf("%s", YEAR), "-%m-%d %H:%M:%S")
#   ),
#   format(
#     as.POSIXlt(norm_ncep$DATE, format = "%d/%m"),
#     paste0(sprintf("%s", YEAR + 1), "-%m-%d %H:%M:%S")
#   )),
#   Z500 = c(norm_ncep$Z500, norm_ncep$Z500),
#   T850 = c(norm_ncep$T850, norm_ncep$T850)
# )
# 
# norms_t2m <- data.frame(
#   DATE_min = c(format(
#     as.POSIXlt(norm$V1, format = "%d/%m %H:%M"),
#     paste0(sprintf("%s", YEAR), "-%m-%d 06:%M:%S")
#   ),
#   format(
#     as.POSIXlt(norm$V1, format = "%d/%m %H:%M"),
#     paste0(sprintf("%s", YEAR + 1), "-%m-%d 06:%M:%S")
#   )),
#   DATE_max = c(format(
#     as.POSIXlt(norm$V3, format = "%d/%m %H:%M"),
#     paste0(sprintf("%s", YEAR), "-%m-%d 18:%M:%S")
#   ),
#   format(
#     as.POSIXlt(norm$V3, format = "%d/%m %H:%M"),
#     paste0(sprintf("%s", YEAR + 1), "-%m-%d 18:%M:%S")
#   )),
#   T2M_min = c(norm$V2, norm$V2),
#   T2M_max = c(norm$V4, norm$V4)
# )

# 
# 
norms_pp <- read.csv(sprintf("../../assets/norms_%s/norms_pp_%s.csv", prof_name, prof_name))


norms_pp$date <- sprintf("%02d", seq(1,12))
                         
norms_pp_past <- norms_pp
norms_pp_now <- norms_pp
norms_pp_future <- norms_pp

norms_pp_past$date <- paste0(format(date_var-years(1), "%Y"),"-",norms_pp$date,"-01")
norms_pp_now$date <- paste0(format(date_var, "%Y"),"-",norms_pp$date,"-01")
norms_pp_future$date <- paste0(format(date_var+years(1), "%Y"),"-",norms_pp$date,"-01")

norms_pp <- 
  merge(norms_pp_past,
        norms_pp_now,
        all.x = TRUE,
        all.y = TRUE)

norms_pp <- 
  merge(norms_pp,
        norms_pp_future,
        all.x = TRUE,
        all.y = TRUE)

norms_df <- read.csv(sprintf("../../assets/norms_%s/norms_df_%s.csv", prof_name, prof_name))

norms_df_past <- norms_df
norms_df_now <- norms_df
norms_df_future <- norms_df

norms_df_past$date <- paste0(format(date_var-years(1), "%Y"),"-",norms_df$subdate)
norms_df_now$date <- paste0(format(date_var, "%Y"),"-",norms_df$subdate)
norms_df_future$date <- paste0(format(date_var+years(1), "%Y"),"-",norms_df$subdate)

if (!leap_year(date_var-years(1)))
{
  norms_df_past <- norms_df_past[-which(grepl("02-29",norms_df_past$date)),]
}

if (!leap_year(date_var))
{
  norms_df_now<- norms_df_now[-which(grepl("02-29",norms_df_now$date)),]
}

if (!leap_year(date_var+years(1)))
{
  norms_df_future <- norms_df_future[-which(grepl("02-29",norms_df_future$date)),]
}

norms_profile <- 
  merge(norms_df_past,
        norms_df_now,
        all.x = TRUE,
        all.y = TRUE)

norms_profile <- 
  merge(norms_profile,
        norms_df_future,
        all.x = TRUE,
        all.y = TRUE)

norms_profile$subdate <- NULL
norms_profile$date <- as_datetime(norms_profile$date) 

barwidth <- 22

get_data <- function(date) {
  if (file.exists(sprintf("../../data/cfs/cfs-%s.csv", date))) {
    thetable <- read.csv(sprintf("../../data/cfs/cfs-%s.csv", date))
  } else {
    thetable <- as.data.frame(t(c(NA, NA, NA, NA, NA, NA, NA)))
  }
  
  names(thetable) <-
    c("runs",
      "dates",
      "profile",
      "geop",
      "tempalt",
      "tempsol",
      "precs")
  return(thetable)
}

date_var <- Sys.Date() - day_ago
```

```{r}
for (i in seq(29, 0, -1)) {
  if (i == 29) {
    allruns <- get_data(str_replace_all(date_var - i, "-", ""))
  } else {
    allruns <-
      rbind(allruns, get_data(str_replace_all(date_var - i, "-", "")))
  }
  
}

if (length(allruns[is.na(allruns)]) != 0) {
  allruns <- allruns[complete.cases(allruns[, -5]), ]
}

allruns <- allruns[order(allruns$dates), ]
allruns <- allruns[which(allruns$profile == prof_name), ]
allruns <- allruns[, -c(3)]

allruns$dates <- as_datetime(allruns$dates)
```



```{r}


the_dates <- sort(unique(allruns$dates))

the_dates <-
  the_dates[(the_dates > toString(format(date_var + 1, "%Y-%m-%d")))]

norms_subset = norms_profile[norms_profile$type == "hgt",]

allruns$geop_dev <-
  allruns$geop - norms_subset[match(allruns$dates,norms_subset$date) ,]$value

norms_subset = norms_profile[norms_profile$type == "t850",]

allruns$tempalt_dev <-
  allruns$tempalt -  norms_subset[match(allruns$dates,norms_subset$date) ,]$value


MONTH_START = round_date(date_var, "month")

if (MONTH_START <= date_var) {
  MONTH_START <- MONTH_START + months(1)
}
```




```{r}
xlist <-
  match(the_dates[which(format(as.POSIXlt(the_dates), "%d %H") == "01 00")], allruns$dates)

the_list <- c(xlist[1])

for (i in seq(2, length(xlist))) {
  the_list <- c(the_list, xlist[i] - 1, xlist[i])
}

the_list <- the_list[1:length(the_list) - 1]

i <- 1


allruns$lab_months <- format(as.POSIXct(allruns$dates), "%B %Y")
allruns$lab_months <-
  ordered(allruns$lab_months, levels = format(as.POSIXct(unique(
    paste0(substr(allruns$dates, 1, 7), "-01")
  )), "%B %Y"))

dstart = match(the_dates[which(format(as.POSIXlt(the_dates)) == MONTH_START)], allruns$dates)[1]

g_plot <-
  ggplot(
    allruns[dstart:the_list[i + 15], ],
    aes(x = as.POSIXct(dates), y = geop_dev)) +
  coord_cartesian(ylim = c(-40, 40)) +
  geom_density_2d_filled(contour_var = "density") +
  facet_wrap(~ lab_months,
             scales = "free_x",
             nrow = 1) +
  scale_color_viridis(option = "B") +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    legend.position = 'none',
    text = element_text(size = 9),
    axis.text.x = element_text(
      angle = 45,
      vjust = 1,
      hjust = 1
    )
  ) +
  scale_y_continuous(
    name = "écart z500",
    breaks = seq(-26, 32, 2),
    labels = seq(-26, 32, 2),
    limits = c(-40, 40),
    expand = c(0, 0)
  ) +
  scale_x_datetime(
    labels = function(x)
      format(x, "%a %d/%m"),
    expand = c(0, 0)
  ) +
  geom_hline(yintercept = 0, color = "white") +
  theme(
    panel.spacing = unit(0, "lines"),
    panel.spacing.x = unit(0.125, "lines"),
    panel.spacing.y = unit(0, "lines"),
    strip.background = element_rect(fill = "black"),
    strip.text.x = element_text(
      size = 10,
      color = "white",
      face = "bold"
    )
  )



h_plot <- ggplot(allruns[dstart:the_list[i + 15], ],
                 aes(x = as.POSIXct(dates), y = tempalt_dev)) +
  coord_cartesian(ylim = c(-20, 20)) +
  geom_density_2d_filled(contour_var = "density") +
  facet_wrap(~ lab_months,
             scales = "free_x",
             nrow = 1) +
  scale_color_viridis(option = "B") +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    legend.position = 'none',
    text = element_text(size = 9),
    axis.text.x = element_text(
      angle = 45,
      vjust = 1,
      hjust = 1
    )
  ) +
  scale_y_continuous(
    name = "écart t850",
    breaks = seq(-16, 16, 2),
    labels = seq(-16, 16, 2),
    limits = c(-20, 20),
    expand = c(0, 0)
  ) +
  scale_x_datetime(
    labels = function(x)
      format(x, "%a %d/%m"),
    expand = c(0, 0)
  ) +
  geom_hline(yintercept = 0, color = "white") +
  theme(
    panel.spacing = unit(0, "lines"),
    panel.spacing.x = unit(0.125, "lines"),
    panel.spacing.y = unit(0, "lines"),
    strip.background = element_rect(fill = "black"),
    strip.text.x = element_text(
      size = 10,
      color = "white",
      face = "bold"
    )
  )


LASTONE <- allruns[the_list[i + 15], ]$dates

```




```{r}



pp_scens <- data.frame(runs = unique(allruns$runs))
colnames(pp_scens) <- c('runs')
allruns$precs_month <- substr(allruns$dates, 1, 7)

steps <- sort(unique(allruns$precs_month))

for (ech in steps) {
  test <- allruns[which(allruns$precs_month == ech), c(1, 2, 6, 10)]
  pp_scens_test <-
    cast(na.omit(test),
         runs ~ precs_month,
         value = 'precs',
         fun.aggregate = sum)
  for (sc in pp_scens_test$runs) {
    if ((sort(test[which(test$runs == sc), "dates"])[1]  != as_datetime(paste0(ech, "-01 UTC"))) |
        (
          sort(test[which(test$runs == sc), "dates"], decreasing = T)[1] !=
          as_datetime(paste0(ech, "-01 UTC")) + months(1) - hours(6)
        )) {
      pp_scens_test[which(pp_scens_test$runs == sc), ech] <- NA
    }
  }
  pp_scens <- merge(pp_scens , pp_scens_test, by.y = 1, all.x = TRUE)
}




rownames(pp_scens) <- pp_scens$runs
pp_scens <-
  pp_scens[, 2:which(names(pp_scens) == format(as.POSIXct(LASTONE), "%Y-%m"))]


colnames(pp_scens) <-
  as.POSIXct(paste(colnames(pp_scens), "01", sep = "-"))

q25 = c()
q50 = c()
q75 = c()
for (i in 1:ncol(pp_scens)) {
  q25 = c(q25,  unlist(unname(summary(pp_scens[, i])[2])))
  q50 = c(q50,  unlist(unname(summary(pp_scens[, i])[3])))
  q75 = c(q75,  unlist(unname(summary(pp_scens[, i])[5])))
}

pp_quartiles <-
  data.frame(
    DATE = colnames(pp_scens),
    Q25 = q25,
    Q50 = q50,
    Q75 = q75
  )


pp_scens_sort <- pp_scens
row.names(pp_scens_sort) <- NULL
for (i in 1:ncol(pp_scens_sort)) {
  replace <- sort(pp_scens_sort[, i], decreasing = T)
  pp_scens_sort[, i] <-
    c(replace, rep(NA, length(pp_scens_sort[, i]) - length(replace)))
}
```




```{r}


pp_scens_sort <-
  pp_scens_sort[, which(names(pp_scens_sort) >= MONTH_START)]

pp_scens_sort <-
  pp_scens_sort[, which(names(pp_scens_sort) < round_date(as.POSIXlt(LASTONE), "month"))]

pp_quartiles <-
  pp_quartiles[which(pp_quartiles$DATE >= MONTH_START), ]

pp_quartiles <-
  pp_quartiles[which(pp_quartiles$DATE < round_date(as.POSIXlt(LASTONE), "month")), ]


colors_bar <- data.frame(rep(NA, nrow(pp_scens_sort)))

for (ech in names(pp_scens_sort)) {
  colors_bar_elem <- c()
  for (i in seq(0, length(na.omit(pp_scens_sort[, ech])) - 1)) {
    colors_bar_elem <-
      c(colors_bar_elem,
        MixColor("cyan", "black", amount1 = abs(length(
          na.omit(pp_scens_sort[, ech])
        ) - i) / length(na.omit(pp_scens_sort[, ech]))))
  }
  colors_bar[, ech] <-
    c(rep(NA, nrow(colors_bar) - length(colors_bar_elem)), colors_bar_elem)
}
colors_bar[, 1] <- NULL


plot_ppall <- ggplot() +
  geom_rect(
    data = pp_scens_sort,
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[1]) - days(10),
      xmax = as.POSIXct(colnames(pp_scens_sort)[1]) + days(10),
      ymin = 0,
      ymax = pp_scens_sort[, 1]
    ),
    color = NA,
    fill = rev(colors_bar[, 1]),
    alpha = 1
  ) +
  geom_rect(
    data = pp_scens_sort,
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[2]) - days(10),
      xmax = as.POSIXct(colnames(pp_scens_sort)[2]) + days(10),
      ymin = 0,
      ymax = pp_scens_sort[, 2]
    ),
    color = NA,
    fill = rev(colors_bar[, 2]),
    alpha = 1
  ) +
  geom_rect(
    data = pp_scens_sort,
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[3]) - days(10),
      xmax = as.POSIXct(colnames(pp_scens_sort)[3]) + days(10),
      ymin = 0,
      ymax = pp_scens_sort[, 3]
    ),
    color = NA,
    fill = rev(colors_bar[, 3]),
    alpha = 1
  ) +
  geom_rect(
    data = pp_scens_sort,
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[4]) - days(10),
      xmax = as.POSIXct(colnames(pp_scens_sort)[4]) + days(10),
      ymin = 0,
      ymax = pp_scens_sort[, 4]
    ),
    color = NA,
    fill = rev(colors_bar[, 4]),
    alpha = 1
  ) +
  geom_rect(
    data = pp_scens_sort,
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[5]) - days(10),
      xmax = as.POSIXct(colnames(pp_scens_sort)[5]) + days(10),
      ymin = 0,
      ymax = pp_scens_sort[, 5]
    ),
    color = NA,
    fill = rev(colors_bar[, 5]),
    alpha = 1
  ) +
  geom_rect(
    data = pp_scens_sort,
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[6]) - days(10),
      xmax = as.POSIXct(colnames(pp_scens_sort)[6]) + days(10),
      ymin = 0,
      ymax = pp_scens_sort[, 6]
    ),
    color = NA,
    fill = rev(colors_bar[, 6]),
    alpha = 1
  )  +
  
  geom_rect(
    data = pp_quartiles[1, ],
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[1]) - days(4),
      xmax = as.POSIXct(colnames(pp_scens_sort)[1]) + days(4),
      ymin = Q25,
      ymax = Q75
    ),
    color = "#808080",
    fill = "grey",
    alpha = 0.4
  ) +
  geom_rect(
    data = pp_quartiles[2, ],
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[2]) - days(4),
      xmax = as.POSIXct(colnames(pp_scens_sort)[2]) + days(4),
      ymin = Q25,
      ymax = Q75
    ),
    color = "#808080",
    fill = "grey",
    alpha = 0.4
  ) +
  geom_rect(
    data = pp_quartiles[3, ],
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[3]) - days(4),
      xmax = as.POSIXct(colnames(pp_scens_sort)[3]) + days(4),
      ymin = Q25,
      ymax = Q75
    ),
    color = "#808080",
    fill = "grey",
    alpha = 0.4
  ) +
  geom_rect(
    data = pp_quartiles[4, ],
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[4]) - days(4),
      xmax = as.POSIXct(colnames(pp_scens_sort)[4]) + days(4),
      ymin = Q25,
      ymax = Q75
    ),
    color = "#808080",
    fill = "grey",
    alpha = 0.4
  ) +
  geom_rect(
    data = pp_quartiles[5, ],
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[5]) - days(4),
      xmax = as.POSIXct(colnames(pp_scens_sort)[5]) + days(4),
      ymin = Q25,
      ymax = Q75
    ),
    color = "#808080",
    fill = "grey",
    alpha = 0.4
  ) +
  geom_rect(
    data = pp_quartiles[6, ],
    mapping = aes(
      xmin = as.POSIXct(colnames(pp_scens_sort)[6]) - days(4),
      xmax = as.POSIXct(colnames(pp_scens_sort)[6]) + days(4),
      ymin = Q25,
      ymax = Q75
    ),
    color = "#808080",
    fill = "grey",
    alpha = 0.4
  )



if (ncol(pp_scens_sort) >= 7) {
  plot_ppall <- plot_ppall +
    geom_rect(
      data = pp_scens_sort,
      mapping = aes(
        xmin = as.POSIXct(colnames(pp_scens_sort)[7]) - days(10),
        xmax = as.POSIXct(colnames(pp_scens_sort)[7]) + days(10),
        ymin = 0,
        ymax = pp_scens_sort[, 7]
      ),
      color = NA,
      fill = rev(colors_bar[, 7]),
      alpha = 1
    )
}

if (ncol(pp_scens_sort) >= 8) {
  plot_ppall <- plot_ppall +
    geom_rect(
      data = pp_scens_sort,
      mapping = aes(
        xmin = as.POSIXct(colnames(pp_scens_sort)[8]) - days(10),
        xmax = as.POSIXct(colnames(pp_scens_sort)[8]) + days(10),
        ymin = 0,
        ymax = pp_scens_sort[, 8]
      ),
      color = NA,
      fill = rev(colors_bar[, 8]),
      alpha = 1
    )
}

if (ncol(pp_scens_sort) >= 9) {
  plot_ppall <- plot_ppall +
    geom_rect(
      data = pp_scens_sort,
      mapping = aes(
        xmin = as.POSIXct(colnames(pp_scens_sort)[9]) - days(10),
        xmax = as.POSIXct(colnames(pp_scens_sort)[9]) + days(10),
        ymin = 0,
        ymax = pp_scens_sort[, 9]
      ),
      color = NA,
      fill = rev(colors_bar[, 9]),
      alpha = 1
    )
}


if (ncol(pp_scens_sort) >= 7) {
  plot_ppall <- plot_ppall +
    geom_rect(
      data = pp_quartiles[7, ],
      mapping = aes(
        xmin = as.POSIXct(colnames(pp_scens_sort)[7]) - days(4),
        xmax = as.POSIXct(colnames(pp_scens_sort)[7]) + days(4),
        ymin = Q25,
        ymax = Q75
      ),
      color = "#808080",
      fill = "grey",
      alpha = 0.4
    )
}

if (ncol(pp_scens_sort) >= 8) {
  plot_ppall <- plot_ppall +
    geom_rect(
      data = pp_quartiles[8, ],
      mapping = aes(
        xmin = as.POSIXct(colnames(pp_scens_sort)[8]) - days(4),
        xmax = as.POSIXct(colnames(pp_scens_sort)[8]) + days(4),
        ymin = Q25,
        ymax = Q75
      ),
      color = "#808080",
      fill = "grey",
      alpha = 0.4
    )
}

if (ncol(pp_scens_sort) >= 9) {
  plot_ppall <- plot_ppall +
    geom_rect(
      data = pp_quartiles[9, ],
      mapping = aes(
        xmin = as.POSIXct(colnames(pp_scens_sort)[9]) - days(4),
        xmax = as.POSIXct(colnames(pp_scens_sort)[9]) + days(4),
        ymin = Q25,
        ymax = Q75
      ),
      color = "#808080",
      fill = "grey",
      alpha = 0.4
    )
}



plot_ppall <-
  plot_ppall +
  theme_linedraw() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.title = element_blank(),
    legend.position = "none",
    panel.background = element_rect(
      fill = "black",
      colour = "black",
      size = 0,
      linetype = "solid"
    )
  ) +
  scale_x_datetime(breaks = as.POSIXct(colnames(pp_scens_sort)),
                   labels = format(as.POSIXct(colnames(pp_scens_sort)), "%B %Y")) +
  scale_y_continuous(
    expand = c(0, 0),
    breaks = seq(0, 200, 10),
    labels = seq(0, 200, 10),
    limits = c(0, 200)
  ) +
  ggtitle(sprintf(
    "PP + NORMs91-20 (Reana NCEP) _ CFS 00z06z12z18z  %s > %s",
    sort(unique(substr(allruns$runs, 1, 10)))[1],
    sort(unique(substr(allruns$runs, 1, 10)), decreasing =
           T)[1]
  )) +
  
  geom_segment(
    data = pp_quartiles,
    aes(
      x = as.POSIXct(DATE) - days(7),
      y = Q50,
      xend = as.POSIXct(DATE) + days(7),
      yend = Q50
    ),
    color = "grey40"
  ) +
geom_line(data = 
            norms_pp[seq(which(norms_pp$date == colnames(pp_scens_sort)[1]),
                         which(norms_pp$date == colnames(pp_scens_sort)[length(colnames(pp_scens_sort))])), ],
          aes(x = as.POSIXct(date), y = total, group = 1),
          color = "white")



```





```{r, echo=F, warning=F, error=F, message=F, results="hide"}
pdf(sprintf("../../data/cfs/cfs-dens_%s.pdf", str_replace_all(date_var, "-", "") ), width = 40, height = 20)
grid.arrange(g_plot,
             h_plot,
             ncol = 1, nrow = 2)

grid.arrange(g_plot,
             plot_ppall,
             ncol = 1, nrow = 2)
dev.off()

png(
  file = sprintf(
    "../../data/cfs/cfs-z500_%s.png",
    str_replace_all(date_var, "-", "")
  ),
  width = 1920,
  height = 540
)
g_plot
dev.off()

png(
  file = sprintf(
    "../../data/cfs/cfs-t850_%s.png",
    str_replace_all(date_var, "-", "")
  ),
  width = 1920,
  height = 540
)
h_plot
dev.off()

png(
  file = sprintf(
    "../../data/cfs/cfs-pp_%s.png",
    str_replace_all(date_var, "-", "")
  ),
  width = 1920,
  height = 540
)
plot_ppall
dev.off()
```


# Densité


Row {.tabset .tabset-fade}
-------------------------------------

### z500

```{r fig.width=25, fig.height=5}
g_plot
```

### t850

```{r fig.width=25, fig.height=5}
h_plot
```

Row {.tabset .tabset-fade}
-------------------------------------

### t850

```{r fig.width=25, fig.height=5}
h_plot
```

### PP Cum



```{r fig.width=25, fig.height=5}
plot_ppall
```


